# Generated by Django 2.2 on 2019-10-29 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('b86f2607-6d40-4fbb-bddb-0a704e8798eb'), verbose_name='Token'),
        ),
    ]
