# Generated by Django 2.2 on 2019-10-28 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191028_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('27747220-e6f5-4f89-bcfb-329a5e6b9ab6'), verbose_name='Token'),
        ),
    ]
