# Generated by Django 2.2 on 2019-10-29 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191028_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('b1fc4b45-75cc-4302-8c6f-68bd568bbe68'), verbose_name='Token'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
