# Generated by Django 2.2 on 2019-10-29 03:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191029_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='git_repo',
            field=models.CharField(blank=True, max_length=125, verbose_name='Ссылка на репозиторий'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('3b47c444-89e5-4711-8c0a-eba7cf27be75'), verbose_name='Token'),
        ),
    ]
