# Generated by Django 2.2 on 2019-11-01 02:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191031_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(max_length=3000, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('417d55e4-aa85-42e4-bfb7-4fba340c109d'), verbose_name='Token'),
        ),
    ]
