# Generated by Django 2.2 on 2019-10-29 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191029_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('1eecd9a4-b39c-4d73-b840-607e493cb33a'), verbose_name='Token'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
