# Generated by Django 2.2 on 2019-11-13 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191106_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='created_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('6a752dd3-9e4b-4227-88f5-3c5abe3d6aa7'), verbose_name='Token'),
        ),
    ]
