# Generated by Django 2.2 on 2019-11-13 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191113_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('6333bb0b-322d-44e6-9fad-92f3a54938ec'), verbose_name='Token'),
        ),
    ]
