# Generated by Django 2.2 on 2019-11-13 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191113_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='created_date',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='updated_date',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('0c324971-6b0c-4340-b249-9a7c5c5971f0'), verbose_name='Token'),
        ),
    ]
