# Generated by Django 2.2 on 2019-12-08 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191113_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('e961997e-fd08-4072-9e65-7fd65c0ad73d'), verbose_name='Token'),
        ),
    ]
