# Generated by Django 2.2 on 2019-10-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191008_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], default='active', max_length=20, null=True, verbose_name='Статус проекта'),
        ),
    ]
