# Generated by Django 2.2 on 2019-11-06 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_projects_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проект'},
        ),
        migrations.AlterModelOptions(
            name='statuses',
            options={'verbose_name': 'Статусы', 'verbose_name_plural': 'Статус'},
        ),
        migrations.AlterModelOptions(
            name='tips',
            options={'verbose_name': 'Типы', 'verbose_name_plural': 'Тип'},
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ussues', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель задачи'),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи'),
        ),
    ]
